------------------------------------------------------------
-- Snowflake Intelligence Monitoring - View Setup
-- Run with a role that has IMPORTED PRIVILEGES on SNOWFLAKE db
------------------------------------------------------------

-- 1. Create database and schemas
CREATE DATABASE IF NOT EXISTS MONITORING_DB;
CREATE SCHEMA IF NOT EXISTS MONITORING_DB.USAGE_MONITORING;
CREATE SCHEMA IF NOT EXISTS MONITORING_DB.AI_OBSERVABILITY;

------------------------------------------------------------
-- 2. Staging views (USAGE_MONITORING schema)
------------------------------------------------------------

CREATE OR REPLACE VIEW MONITORING_DB.USAGE_MONITORING.STG_ROLE_TAGS(
    ROLE_NAME,
    COUNTRY,
    DIVISION,
    APPLICATION
) AS (
    WITH tagging AS (
        SELECT
            tr.OBJECT_NAME AS ROLE_NAME,
            TAG_NAME,
            TAG_VALUE
        FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES tr
        WHERE TAG_NAME IN ('TAG_COUNTRY','TAG_DIVISION','TAG_APPLICATION')
          AND tr.DOMAIN = 'ROLE'
    )
    SELECT
        $1::TEXT AS ROLE_NAME,
        $2::TEXT AS COUNTRY,
        $3::TEXT AS DIVISION,
        $4::TEXT AS APPLICATION
    FROM tagging
    PIVOT(MAX(TAG_VALUE) FOR TAG_NAME IN ('TAG_COUNTRY', 'TAG_DIVISION', 'TAG_APPLICATION')) AS p
);

CREATE OR REPLACE VIEW MONITORING_DB.USAGE_MONITORING.STG_SNOWFLAKE_INTELLIGENCE(
    ACCOUNT_NAME,
    USAGE_DATE,
    RATING_TYPE,
    SERVICE_TYPE,
    CATEGORY,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    TOKENS,
    TOKEN_CREDITS,
    USER_NAME,
    USER_TAGS,
    ROLE_NAME,
    COUNTRY,
    DIVISION,
    APPLICATION,
    REQUEST_ID,
    DATABASE_NAME,
    SCHEMA_NAME,
    AGENT_NAME,
    AGENT_TAGS,
    TOKENS_GRANULAR,
    CREDITS_GRANULAR,
    METADATA
) AS (
    SELECT
        CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME,
        CONVERT_TIMEZONE('UTC', TO_TIMESTAMP_LTZ(START_TIME))::DATE AS USAGE_DATE,
        'AI COMPUTE' AS RATING_TYPE,
        'SNOWFLAKE INTELLIGENCE' AS SERVICE_TYPE,
        'SNOWFLAKE INTELLIGENCE' AS CATEGORY,
        NULL AS WAREHOUSE_NAME,
        NULL AS WAREHOUSE_SIZE,
        TOKENS,
        TOKEN_CREDITS::FLOAT AS TOKEN_CREDITS,
        USER_NAME,
        USER_TAGS,
        tg.ROLE_NAME,
        tg.COUNTRY,
        tg.DIVISION,
        tg.APPLICATION,
        REQUEST_ID,
        AGENT_DATABASE_NAME AS DATABASE_NAME,
        AGENT_SCHEMA_NAME AS SCHEMA_NAME,
        AGENT_NAME,
        AGENT_TAGS,
        TOKENS_GRANULAR,
        CREDITS_GRANULAR,
        METADATA
    FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_INTELLIGENCE_USAGE_HISTORY ai
    LEFT JOIN MONITORING_DB.USAGE_MONITORING.STG_ROLE_TAGS tg
        ON METADATA:"role_name"::TEXT = tg.ROLE_NAME
);

CREATE OR REPLACE VIEW MONITORING_DB.USAGE_MONITORING.STG_CORTEX_AGENT(
    ACCOUNT_NAME,
    USAGE_DATE,
    RATING_TYPE,
    SERVICE_TYPE,
    CATEGORY,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    TOKENS,
    TOKEN_CREDITS,
    USER_NAME,
    USER_TAGS,
    ROLE_NAME,
    COUNTRY,
    DIVISION,
    APPLICATION,
    REQUEST_ID,
    DATABASE_NAME,
    SCHEMA_NAME,
    AGENT_NAME,
    AGENT_TAGS,
    TOKENS_GRANULAR,
    CREDITS_GRANULAR,
    METADATA
) AS (
    SELECT
        CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME,
        CONVERT_TIMEZONE('UTC', TO_TIMESTAMP_LTZ(START_TIME))::DATE AS USAGE_DATE,
        'AI COMPUTE' AS RATING_TYPE,
        'CORTEX AGENTS' AS SERVICE_TYPE,
        'CORTEX AGENTS' AS CATEGORY,
        NULL AS WAREHOUSE_NAME,
        NULL AS WAREHOUSE_SIZE,
        TOKENS,
        TOKEN_CREDITS::FLOAT AS TOKEN_CREDITS,
        USER_NAME,
        USER_TAGS,
        tg.ROLE_NAME,
        tg.COUNTRY,
        tg.DIVISION,
        tg.APPLICATION,
        REQUEST_ID,
        AGENT_DATABASE_NAME AS DATABASE_NAME,
        AGENT_SCHEMA_NAME AS SCHEMA_NAME,
        AGENT_NAME,
        AGENT_TAGS,
        TOKENS_GRANULAR,
        CREDITS_GRANULAR,
        METADATA
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY ai
    LEFT JOIN MONITORING_DB.USAGE_MONITORING.STG_ROLE_TAGS tg
        ON METADATA:"role_name"::TEXT = tg.ROLE_NAME
);

------------------------------------------------------------
-- 3. AI Observability views
------------------------------------------------------------

CREATE OR REPLACE VIEW MONITORING_DB.AI_OBSERVABILITY.STG_SNOWFLAKE_INTELLIGENCE_OBSERVABILITY(
    AGENT_NAME,
    THREAD_ID,
    REQUEST_ID,
    INPUT_ID,
    SESSION_ID,
    ROLE_ID,
    ROLE_NAME,
    USER_ID,
    USER_NAME,
    OBSERVED_TIMESTAMP,
    DURATION,
    RECORD_DETAILS,
    CORTEX_ANALYST_FLAG,
    CORTEX_SEARCH_FLAG,
    CORTEX_CHART_FLAG,
    CUSTOM_TOOLS_FLAG,
    REQUEST_STATUS_DETAILS,
    STATUS,
    PLANNING_CUSTOM_ORCHESTRATION_INSTRUCTIONS,
    PLANNING_INSTRUCTIONS,
    PLANNING_MESSAGES,
    PLANNING_MODEL,
    PLANNING_QUERY,
    PLANNING_RESPONSE,
    PLANNING_TOKEN_COUNT_CACHE_READ_INPUT,
    PLANNING_TOKEN_COUNT_CACHE_WRITE_INPUT,
    PLANNING_TOKEN_COUNT_INPUT,
    PLANNING_TOKEN_COUNT_OUTPUT,
    PLANNING_TOKEN_COUNT_PLAN,
    PLANNING_TOKEN_COUNT_TOTAL,
    PLANNING_TOOL_DESCRIPTION,
    PLANNING_TOOL_NAME,
    PLANNING_TOOL_PARAMETERS,
    PLANNING_TOOL_TYPE,
    PLANNING_TOOL_EXECUTION_ARGUMENT_NAME,
    PLANNING_TOOL_EXECUTION_ARGUMENT_VALUE,
    PLANNING_TOOL_EXECUTION_ID,
    PLANNING_TOOL_EXECUTION_NAME,
    PLANNING_TOOL_EXECUTION_RESULTS,
    FEEDBACK,
    FEEDBACK_MESSAGE
) AS (
    SELECT
        RECORD_ATTRIBUTES:"snow.ai.observability.object.name"::TEXT AS AGENT_NAME,
        RECORD_ATTRIBUTES:"snow.ai.observability.agent.thread_id"::INTEGER AS THREAD_ID,
        RECORD_ATTRIBUTES:"ai.observability.record_id"::TEXT AS REQUEST_ID,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"ai.observability.input_id"::TEXT)[0]::TEXT AS INPUT_ID,
        ARRAY_AGG(DISTINCT RESOURCE_ATTRIBUTES:"snow.session.id"::TEXT) AS SESSION_ID,
        RESOURCE_ATTRIBUTES:"snow.session.role.primary.id"::TEXT AS ROLE_ID,
        RESOURCE_ATTRIBUTES:"snow.session.role.primary.name"::TEXT AS ROLE_NAME,
        RESOURCE_ATTRIBUTES:"snow.user.id"::TEXT AS USER_ID,
        RESOURCE_ATTRIBUTES:"snow.user.name"::TEXT AS USER_NAME,
        COALESCE(MIN(OBSERVED_TIMESTAMP), MIN(TIMESTAMP), MIN(START_TIMESTAMP)) AS OBSERVED_TIMESTAMP,
        SUM(RECORD_ATTRIBUTES:"snow.ai.observability.agent.duration"::INTEGER) AS DURATION,
        ARRAY_AGG(DISTINCT RECORD:"name"::TEXT) AS RECORD_DETAILS,
        ARRAY_TO_STRING(RECORD_DETAILS, ',') ILIKE '%CortexAnalyst%' AS CORTEX_ANALYST_FLAG,
        ARRAY_TO_STRING(RECORD_DETAILS, ',') ILIKE '%CortexSearchService%' AS CORTEX_SEARCH_FLAG,
        ARRAY_TO_STRING(RECORD_DETAILS, ',') ILIKE '%CortexChart%' AS CORTEX_CHART_FLAG,
        ARRAY_TO_STRING(RECORD_DETAILS, ',') ILIKE '%ToolCall%' AS CUSTOM_TOOLS_FLAG,
        OBJECT_CONSTRUCT(
            'record', ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.status"),
            'planning', ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.status"),
            'sql_execution', ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.tool.sql_execution.status"),
            'cortex_search', ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.tool.cortex_search.status"),
            'cortex_analyst', ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.tool.cortex_analyst.status"),
            'custom_tools', ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.tool.custom_tool.status")
        ) AS REQUEST_STATUS_DETAILS,
        CASE
            WHEN ARRAY_TO_STRING(REQUEST_STATUS_DETAILS:"record", ',') = 'ERROR' THEN 'Failed'
            WHEN ARRAY_TO_STRING(REQUEST_STATUS_DETAILS:"planning", ',') LIKE '%ERROR%' THEN 'Finished with Errors'
            WHEN ARRAY_TO_STRING(REQUEST_STATUS_DETAILS:"sql_execution", ',') LIKE '%ERROR%' THEN 'Finished with Errors'
            WHEN ARRAY_TO_STRING(REQUEST_STATUS_DETAILS:"cortex_analyst", ',') LIKE '%ERROR%' THEN 'Finished with Errors'
            WHEN ARRAY_TO_STRING(REQUEST_STATUS_DETAILS:"cortex_search", ',') LIKE '%ERROR%' THEN 'Finished with Errors'
            WHEN ARRAY_TO_STRING(REQUEST_STATUS_DETAILS:"custom_tools", ',') LIKE '%ERROR%' THEN 'Finished with Errors'
            ELSE 'Successfully Finished'
        END AS STATUS,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.custom_orchestration_instructions"::TEXT)[0]::TEXT AS PLANNING_CUSTOM_ORCHESTRATION_INSTRUCTIONS,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.instruction"::TEXT)[0]::TEXT AS PLANNING_INSTRUCTIONS,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.messages"::TEXT) AS PLANNING_MESSAGES,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.model"::TEXT)[0]::TEXT AS PLANNING_MODEL,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.query"::TEXT)[0]::TEXT AS PLANNING_QUERY,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.response"::TEXT)[0]::TEXT AS PLANNING_RESPONSE,
        SUM(RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.token_count.cache_read_input"::INTEGER) AS PLANNING_TOKEN_COUNT_CACHE_READ_INPUT,
        SUM(RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.token_count.cache_write_input"::INTEGER) AS PLANNING_TOKEN_COUNT_CACHE_WRITE_INPUT,
        SUM(RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.token_count.input"::INTEGER) AS PLANNING_TOKEN_COUNT_INPUT,
        SUM(RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.token_count.output"::INTEGER) AS PLANNING_TOKEN_COUNT_OUTPUT,
        SUM(RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.token_count.plan"::INTEGER) AS PLANNING_TOKEN_COUNT_PLAN,
        SUM(RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.token_count.total"::INTEGER) AS PLANNING_TOKEN_COUNT_TOTAL,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool.description"::TEXT)[0]::TEXT AS PLANNING_TOOL_DESCRIPTION,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool.name"::TEXT) AS PLANNING_TOOL_NAME,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool.parameters"::TEXT) AS PLANNING_TOOL_PARAMETERS,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool.type"::TEXT) AS PLANNING_TOOL_TYPE,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool_execution.argument.name"::TEXT) AS PLANNING_TOOL_EXECUTION_ARGUMENT_NAME,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool_execution.argument.value"::TEXT) AS PLANNING_TOOL_EXECUTION_ARGUMENT_VALUE,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool_execution.id"::TEXT) AS PLANNING_TOOL_EXECUTION_ID,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool_execution.name"::TEXT) AS PLANNING_TOOL_EXECUTION_NAME,
        ARRAY_AGG(DISTINCT RECORD_ATTRIBUTES:"snow.ai.observability.agent.planning.tool_execution.results"::TEXT) AS PLANNING_TOOL_EXECUTION_RESULTS,
        CASE
            ARRAY_AGG(VALUE:"positive") WITHIN GROUP (ORDER BY OBSERVED_TIMESTAMP DESC)[0]::TEXT
            WHEN 'true' THEN 'Positive'
            WHEN 'false' THEN 'Negative'
        END AS FEEDBACK,
        ARRAY_AGG(VALUE:"feedback_message") WITHIN GROUP (ORDER BY OBSERVED_TIMESTAMP DESC)[0]::TEXT AS FEEDBACK_MESSAGE
    FROM SNOWFLAKE.LOCAL.AI_OBSERVABILITY_EVENTS tr
    WHERE 1 = 1
      AND SCOPE:"name"::TEXT = 'snow.cortex.agent'
    GROUP BY ALL
);

------------------------------------------------------------
-- 4. Fact / reporting views (AI_OBSERVABILITY schema)
------------------------------------------------------------

CREATE OR REPLACE VIEW MONITORING_DB.AI_OBSERVABILITY.SNOWFLAKE_INTELLIGENCE_REQUESTS(
    REQUEST_ID,
    REQUEST_SOURCE,
    USAGE_DATE,
    USER_NAME,
    ROLE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    AGENT_NAME,
    AGENT_TAGS,
    STATUS,
    REQUEST_STATUS_DETAILS,
    DURATION,
    PLANNING_CUSTOM_ORCHESTRATION_INSTRUCTIONS,
    PLANNING_INSTRUCTIONS,
    RECORD_DETAILS,
    CORTEX_ANALYST_FLAG,
    CORTEX_SEARCH_FLAG,
    CORTEX_CHART_FLAG,
    CUSTOM_TOOLS_FLAG,
    PLANNING_MESSAGES,
    PLANNING_MODEL,
    PLANNING_QUERY,
    PLANNING_RESPONSE,
    FEEDBACK,
    FEEDBACK_MESSAGE
) AS (
    SELECT
        si.REQUEST_ID,
        'Snowflake Intelligence' AS REQUEST_SOURCE,
        si.USAGE_DATE,
        si.USER_NAME,
        ob.ROLE_NAME,
        si.DATABASE_NAME,
        si.SCHEMA_NAME,
        si.AGENT_NAME,
        si.AGENT_TAGS,
        ob.STATUS,
        ob.REQUEST_STATUS_DETAILS,
        ob.DURATION,
        ob.PLANNING_CUSTOM_ORCHESTRATION_INSTRUCTIONS,
        ob.PLANNING_INSTRUCTIONS,
        ob.RECORD_DETAILS,
        ob.CORTEX_ANALYST_FLAG,
        ob.CORTEX_SEARCH_FLAG,
        ob.CORTEX_CHART_FLAG,
        ob.CUSTOM_TOOLS_FLAG,
        ob.PLANNING_MESSAGES,
        ob.PLANNING_MODEL,
        ob.PLANNING_QUERY,
        ob.PLANNING_RESPONSE,
        ob.FEEDBACK,
        ob.FEEDBACK_MESSAGE
    FROM MONITORING_DB.USAGE_MONITORING.STG_SNOWFLAKE_INTELLIGENCE si
    LEFT JOIN MONITORING_DB.AI_OBSERVABILITY.STG_SNOWFLAKE_INTELLIGENCE_OBSERVABILITY ob
        ON si.REQUEST_ID = ob.REQUEST_ID

    UNION ALL

    SELECT
        si.REQUEST_ID,
        'Agent' AS REQUEST_SOURCE,
        si.USAGE_DATE,
        si.USER_NAME,
        ob.ROLE_NAME,
        si.DATABASE_NAME,
        si.SCHEMA_NAME,
        si.AGENT_NAME,
        si.AGENT_TAGS,
        ob.STATUS,
        ob.REQUEST_STATUS_DETAILS,
        ob.DURATION,
        ob.PLANNING_CUSTOM_ORCHESTRATION_INSTRUCTIONS,
        ob.PLANNING_INSTRUCTIONS,
        ob.RECORD_DETAILS,
        ob.CORTEX_ANALYST_FLAG,
        ob.CORTEX_SEARCH_FLAG,
        ob.CORTEX_CHART_FLAG,
        ob.CUSTOM_TOOLS_FLAG,
        ob.PLANNING_MESSAGES,
        ob.PLANNING_MODEL,
        ob.PLANNING_QUERY,
        ob.PLANNING_RESPONSE,
        ob.FEEDBACK,
        ob.FEEDBACK_MESSAGE
    FROM MONITORING_DB.USAGE_MONITORING.STG_CORTEX_AGENT si
    LEFT JOIN MONITORING_DB.AI_OBSERVABILITY.STG_SNOWFLAKE_INTELLIGENCE_OBSERVABILITY ob
        ON si.REQUEST_ID = ob.REQUEST_ID
);

CREATE OR REPLACE VIEW MONITORING_DB.AI_OBSERVABILITY.FACT_SNOWFLAKE_INTELLIGENCE_REQUESTS_DETAILS(
    REQUEST_ID,
    USAGE_DATE,
    USER_NAME,
    CHILD_REQUEST_ID,
    REQUEST_TYPE,
    LLM,
    START_TIME,
    TOKENS_READ_INPUT,
    TOKENS_WRITE_INPUT,
    TOKENS_INPUT,
    TOKENS_OUTPUT,
    CREDITS_READ_INPUT,
    CREDITS_WRITE_INPUT,
    CREDITS_INPUT,
    CREDITS_OUTPUT
) AS (
    SELECT
        si.REQUEST_ID,
        si.USAGE_DATE,
        si.USER_NAME,
        OBJECT_KEYS(t1.VALUE)[0]::TEXT AS CHILD_REQUEST_ID,
        t2.KEY AS REQUEST_TYPE,
        t3.KEY AS LLM,
        t1.VALUE[OBJECT_KEYS(t1.VALUE)[0]]:"start_time"::TIMESTAMP_TZ AS START_TIME,
        COALESCE(t3.VALUE:"cache_read_input", 0)::INTEGER AS TOKENS_READ_INPUT,
        COALESCE(t3.VALUE:"cache_write_input", 0)::INTEGER AS TOKENS_WRITE_INPUT,
        COALESCE(t3.VALUE:"input", 0)::INTEGER AS TOKENS_INPUT,
        COALESCE(t3.VALUE:"output", 0)::INTEGER AS TOKENS_OUTPUT,
        COALESCE(TRY_PARSE_JSON(CREDITS_GRANULAR[t1.INDEX])[OBJECT_KEYS(t1.VALUE)[0]][t2.KEY][t3.KEY]:"cache_read_input", 0)::FLOAT AS CREDITS_READ_INPUT,
        COALESCE(TRY_PARSE_JSON(CREDITS_GRANULAR[t1.INDEX])[OBJECT_KEYS(t1.VALUE)[0]][t2.KEY][t3.KEY]:"cache_write_input", 0)::FLOAT AS CREDITS_WRITE_INPUT,
        COALESCE(TRY_PARSE_JSON(CREDITS_GRANULAR[t1.INDEX])[OBJECT_KEYS(t1.VALUE)[0]][t2.KEY][t3.KEY]:"input", 0)::FLOAT AS CREDITS_INPUT,
        COALESCE(TRY_PARSE_JSON(CREDITS_GRANULAR[t1.INDEX])[OBJECT_KEYS(t1.VALUE)[0]][t2.KEY][t3.KEY]:"output", 0)::FLOAT AS CREDITS_OUTPUT
    FROM MONITORING_DB.USAGE_MONITORING.STG_CORTEX_AGENT si,
        LATERAL FLATTEN(INPUT => TOKENS_GRANULAR, OUTER => TRUE) t1,
        LATERAL FLATTEN(INPUT => TRY_PARSE_JSON(t1.VALUE)[OBJECT_KEYS(t1.VALUE)[0]], OUTER => TRUE, MODE => 'OBJECT') t2,
        LATERAL FLATTEN(INPUT => t2.VALUE, OUTER => TRUE) t3
    WHERE 1 = 1
      AND t2.KEY != 'start_time'
);

CREATE OR REPLACE VIEW MONITORING_DB.AI_OBSERVABILITY.FACT_SNOWFLAKE_INTELLIGENCE_DAY_USER_AGG(
    USER_NAME,
    USAGE_DATE,
    SPEND_USD
) AS (
    SELECT
        USER_NAME,
        USAGE_DATE,
        SUM(CREDITS_INPUT + CREDITS_OUTPUT + CREDITS_READ_INPUT + CREDITS_WRITE_INPUT * 3.7) AS SPEND_USD
    FROM MONITORING_DB.AI_OBSERVABILITY.FACT_SNOWFLAKE_INTELLIGENCE_REQUESTS_DETAILS
    WHERE 1 = 1
    GROUP BY ALL
    ORDER BY 1 DESC, 2
);

