------------------------------------------------------------
-- Grant access (replace <YOUR_ROLE> with your app role)
------------------------------------------------------------

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE <YOUR_ROLE>;
GRANT USAGE ON DATABASE MONITORING_DB TO ROLE <YOUR_ROLE>;
GRANT USAGE ON SCHEMA MONITORING_DB.USAGE_MONITORING TO ROLE <YOUR_ROLE>;
GRANT USAGE ON SCHEMA MONITORING_DB.AI_OBSERVABILITY TO ROLE <YOUR_ROLE>;
GRANT SELECT ON ALL VIEWS IN SCHEMA MONITORING_DB.USAGE_MONITORING TO ROLE <YOUR_ROLE>;
GRANT SELECT ON ALL VIEWS IN SCHEMA MONITORING_DB.AI_OBSERVABILITY TO ROLE <YOUR_ROLE>;
